# Configuración servidor FTP DEAW
# Autor: Jorge Garre Corrales

# a) El servidor se inicia en modo standalone
listen=YES
listen_ipv6=NO

# b) Mensaje de bienvenida del servidor
ftpd_banner=--- Welcome to the FTP server of jorge.garre.test ---

# c) Mensaje para usuarios anónimos al acceder
dirmessage_enable=YES

# d) Se cerrarán las conexiones que estén inactivas más de 720 segundos.
idle_session_timeout=720

# e) Los usuarios con cuenta podrán usar hasta 5 MB/s de ancho de banda.
local_max_rate=5242880

# f) Los usuarios anónimos solo podrán usar hasta 2 MB/s de ancho de banda.
anon_max_rate=2097152 

# g) Se permitirá acceso a usuarios anónimos de forma que puedan descargar archivos y no
# puedan subir archivos.
anonymous_enable=YES
write_enable=NO
anon_upload_enable=NO
anon_mkdir_write_enable=NO
anon_other_write_enable=NO
anon_world_readable_only=YES

# h) Permitir acceso a usuarios locales para subir y descargar archivos
local_enable=YES
write_enable=YES
allow_writeable_chroot=YES

# i) Solo la usuaria maria no estará enjaulada, el resto sí
chroot_local_user=YES
chroot_list_enable=YES
chroot_list_file=/etc/vsftpd.chroot_list





local_enable=YES

xferlog_enable=YES

connect_from_port_20=YES

secure_chroot_dir=/var/run/vsftpd/empty

pam_service_name=vsftpd

rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=NO

